export const OVERVIEW_LIST = [
  {
    id: 0,
    corpCode: '000',
    firmName: '주식회사 가가가',
    bizrNo: '000',
    jurirNo: '000',
    stockCode: '000',
    conglomerateName: '주식회사 모회사',
    ceoName: '김아무개',
    establishDate: '2023-02-20',
    adress1: '서울',
    adress2: '강남구',
    homepageUrl: null,
  },
  {
    id: 1,
    corpCode: '001',
    firmName: '주식회사 나나나',
    bizrNo: '0021',
    jurirNo: '1021',
    stockCode: '2131',
    conglomerateName: '주식회사 모회사',
    ceoName: '김아무개',
    establishDate: '2023-02-03',
    adress1: '서울',
    adress2: '강북구',
    homepageUrl: null,
  },
  {
    id: 2,
    corpCode: '102',
    firmName: '노른자',
    bizrNo: '123',
    jurirNo: '6575',
    stockCode: '3543',
    conglomerateName: '달걀',
    ceoName: '박거란',
    establishDate: '1998-09-09',
    adress1: '대전',
    adress2: '유성구',
    homepageUrl: 'https://google.com/',
  },
  {
    id: 3,
    corpCode: '178',
    firmName: '모회사',
    bizrNo: '39',
    jurirNo: '20',
    stockCode: '023',
    conglomerateName: null,
    ceoName: '모모',
    establishDate: '1990-09-03',
    adress1: '서울',
    adress2: '강남구',
    homepageUrl: null,
  },
];
