export const SIDENAV_DATA = {
  data: [
    {
      domainId: 1,
      domainCode: 'IH',
      domainName: 'ICT HW',
      industryClassId: 1,
      industryClassCode: 'IHCSC',
      industryClassName: '반도체/부품/장비',
      subClassId: 1,
      subClassName: 'WAFER & MASK',
      subClassCode: 'A',
      subClassLevel: 1,
    },
    {
      domainId: 1,
      domainCode: 'IH',
      domainName: 'ICT HW',
      industryClassId: 1,
      industryClassCode: 'IHCSC',
      industryClassName: '반도체/부품/장비',
      subClassId: 2,
      subClassName: 'FABRICATION',
      subClassCode: 'A10',
      subClassLevel: 2,
    },
    {
      domainId: 1,
      domainCode: 'IH',
      domainName: 'ICT HW',
      industryClassId: 1,
      industryClassCode: 'IHCSC',
      industryClassName: '반도체/부품/장비',
      subClassId: 3,
      subClassName: 'ASSEMBLY & TEST',
      subClassCode: 'A20',
      subClassLevel: 2,
    },
    {
      domainId: 1,
      domainCode: 'IH',
      domainName: 'ICT HW',
      industryClassId: 1,
      industryClassCode: 'IHCSC',
      industryClassName: '반도체/부품/장비',
      subClassId: 4,
      subClassName: 'Discrete',
      subClassCode: 'A10010',
      subClassLevel: 3,
    },
  ],
};
