import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Footer from '@/components/base/footer/footer';
import Header from '@/components/base/header/header';
import Sidebar from '@/components/base/sidebar/sidebar';

import styles from './layout.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Providers> */}
        <div className={styles.container}>
          <Sidebar />
          <main className={styles.main}>
            <Header />
            <div className={styles.content}>{children}</div>
            <Footer />
          </main>
        </div>
        {/* </Providers> */}
      </body>
    </html>
  );
}
