import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Footer from '@/components/base/footer';
import Header from '@/components/base/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Map of Value Chain',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="min-h-[calc(100vh-3.5rem)] flex flex-col justify-between">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
