version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.config:/etc/nginx/nginx.conf
      - ./docker_data/log/nginx:/var/log/nginx
    depends_on:
      - dash
    networks:
      - app

  dash:
    build:
      context: ./dash
      dockerfile: Dockerfile
    container_name: dash
    volumes:
      - ./dash:/app
      - ./docker_data/log/dash:/var/log
    networks:
      - app
    expose:
      - 8050

networks:
  app:
    driver: bridge
